CREATE ROLE app WITH LOGIN PASSWORD 'app' CREATEDB SUPERUSER;

CREATE DATABASE flashcards OWNER app;

\connect flashcards
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
ALTER SCHEMA public OWNER TO app;